# Generated by Django 3.2.16 on 2023-01-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование компани')),
                ('type', models.CharField(max_length=512, verbose_name='Тип компани')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес компани')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование события')),
                ('poster', models.ImageField(upload_to='posters', verbose_name='Картинка-постер события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=512, verbose_name='Источник события')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Тип события')),
            ],
        ),
    ]
